### ISSUE TITLE
Why this project do not support libtorch 1.12 +?

### ISSUE THREAD

**Issue by DeepSpace98** [mszhanyi/VSIXTorch#10]
I see your has said it support libtorch 1.12+,but the [vsixtorch](https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001) don't support ,when I want to create a project, it said  it can't find my libtorch1.12.0+cu116.

**Comment by mszhanyi** [comment]
did you upgrade it to the latest version (0.5.0)?
I just tried a moment ago, it works

**Comment by DeepSpace98** [comment]
> 您是否将其升级到最新版本（0.5.0）？ 我刚才试过了，它有效


I think I know what the problem is that int the path,  my torch path is `D:\libtorch\libtorch-win-shared-with-deps-1.12.0+cu116`,but actually it should be `D:\libtorch\libtorch-win-shared-with-deps-1.12.0+cu116\libtorch`. when I change the path, it work successfully.
