### ISSUE TITLE
Can not install on VS2022

### ISSUE THREAD

**Issue by bitnick10** [mszhanyi/VSIXTorch#12]
error log:
找到的已安装产品 - Visual Studio Community 2022
VSIXInstaller.NoApplicableSKUsException: 此扩展不能安装在任何当前安装的产品上。
   在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

download from https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001

**Comment by mszhanyi** [comment]
sorry, so far, this extension only supports VS 2019
