### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by lvshengqiangh** [mszhanyi/VSIXTorch#13]
why when I craat a new project, it prompts that libtorch is not in the folder

**Comment by mszhanyi** [comment]
![image](https://user-images.githubusercontent.com/16190118/195769409-a7db8da7-8bae-4f5f-8b29-09f35b512222.png)

@lsq-xh   did you unzip it and select the folder

**Comment by lvshengqiangh** [comment]
yes,i did,but it did not work.
![image](https://user-images.githubusercontent.com/114467134/200344120-f8c24d60-6a56-430b-85e3-1dbae62a350f.png)
![image](https://user-images.githubusercontent.com/114467134/200344341-7d751186-f1c6-4282-8071-425c44fc0fdf.png)

**Comment by mszhanyi** [comment]
@lsq-xh 
The error message is clear.
Your libtorch is in the root dir of D drive. Did you try selecting D rather than `d:\libtorch`
