### ISSUE TITLE
vstemplate 文件引用的向导类不存。

### ISSUE THREAD

**Issue by lemi-lu** [mszhanyi/VSIXTorch#18]
i used visual studio 2019，download the LibTorch Project and installed，there was an error when i created the preject。 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/34082221/211256436-53c6502d-9a6f-4a61-be37-eed0776dd424.png)
@mszhanyi   thank you.

**Comment by mszhanyi** [comment]
@luhaoming117 
Thank your reporting very much.
Could you please download the latest 0.8.3 in marketplace and reinstall it in VS 2019?

**Comment by lemi-lu** [comment]
@mszhanyi 
Great ,it's working. 
Thanks very much.
