### ISSUE TITLE
Torch 2.O is not yet supported

### ISSUE THREAD

**Issue by HichemMaiza** [mszhanyi/VSIXTorch#21]
Hello @mszhanyi @mantaionut, any plans to support Torch 2.0 in the near future ? Thank you. 
Could you give some instructions on how to add a new version, build the plugin and submit a pull request ? Thank you

**Comment by mszhanyi** [comment]
@HichemMaiza , Thank your reminder! PyTorch 2.0 has been supported. Could you please install the latest Extension.
