### ISSUE TITLE
visual studio 2022 CPU only installation 

### ISSUE THREAD

**Issue by MohamadOHijazi** [mszhanyi/VSIXTorch#27]
Thanks for your significant contribution, does your project support the CPU version of Pytorch? also, it's best if you specify the SDKs needed. thanks in advanced.

**Comment by mszhanyi** [comment]
Yes, it supports the CPU version of Pytorch.
You only need to specify the directory of the CPU only binaries.

**Comment by MohamadOHijazi** [comment]
I did add to the linker input torch-cpu.lib however in every build the program generated the erreor torch-cpu.dll not found.  Any further help is greatly appreciated.

**Comment by mszhanyi** [comment]
![image](https://github.com/mszhanyi/VSIXTorch/assets/16190118/7a9da723-ce0c-4b42-8de8-dcd59a823a65)

**Comment by mszhanyi** [comment]
1. download the CPU binaries from pytorch.org and unzip it.
2. open VS2022, select Torch Project
3. Select the folder you unzipped

**Comment by MohamadOHijazi** [comment]
Their is a bug in pytorch 2.1 cpu only version.
I followed the same steps with version 2.0 qnd it worked as expected. 
Thanks for your fast response.
