### ISSUE TITLE
Copying libtorch dlls fails due to space character in path 

### ISSUE THREAD

**Issue by IanWood1** [mszhanyi/VSIXTorch#30]
I had an issue where the following command failed because there was a space in the $torch_debug_dir$ path. The easy fix was the put quotations around the path to the lib folder and to the Debug folder. Changes were made in Project Properties > Build Events > Post-Build Event > Command Line. The issue was from example-app.vcxproj on line 93:

`<Command>setlocal
xcopy $torch_debug_dir$\libtorch\lib $destinationdirectory$\x64\Debug /D /Y
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal &amp; call :cmErrorLevel %errorlevel% &amp; goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd</Command>`

**Comment by mszhanyi** [comment]
Thank your finding very much. I'll fix it soon.

**Comment by mszhanyi** [comment]
fixed
