### ISSUE TITLE
torch 2.1 isn't supported yet

### ISSUE THREAD

**Issue by laurabalascuta** [mszhanyi/VSIXTorch#31]
I am trying to create a new project using VSIXTorch and I get this error saying that "torch 2.1 isn't supported yet".
![image](https://github.com/mszhanyi/VSIXTorch/assets/80290296/92fa9069-fe54-4a19-8034-b6fcdec8b343)

Any ideas on how to overcome this issue?
Thank you!

**Comment by PitrakSarkar** [comment]
even i am facing the same issue. I am using cuda 12.1 environment

**Comment by mszhanyi** [comment]
Thank your feedbacks. I've updated the package.
Please upgrade to the latest version which supports torch2.1
