### ISSUE TITLE
Error: Torch 2.2 isn't supported yet.

### ISSUE THREAD

**Issue by ghost** [mszhanyi/VSIXTorch#33]
Can you upgrade the project to Torch 2.2, please?
<img width="412" alt="image" src="https://github.com/mszhanyi/VSIXTorch/assets/101401282/f2d7a2d1-5347-452a-87b7-43f53cfb87c1">

**Comment by mszhanyi** [comment]
Upgraded. 
Could you please upgrade to the latest version.
