### ISSUE TITLE
Can not configure libtorch in vs2019.

### ISSUE THREAD

**Issue by jlnotgm** [mszhanyi/VSIXTorch#36]
Click the "OK" button on the Project Settings interface. The program did not successfully configure Libtorch. It just created a new "TorchProject1" folder and then deleted it immediately.
![fc](https://github.com/mszhanyi/VSIXTorch/assets/165656411/1fbd3ed6-e42d-45c4-9639-62e9e1ef1b61)

**Comment by mszhanyi** [comment]
@jinotgm, Thank you very much for reporting it.
I've fixed and released the new package.
Could you please upgrade it?

**Comment by jlnotgm** [comment]
The new package works fine, thanks!
