### ISSUE TITLE
LibTorch C++ project template issue in visual studio 2019

### ISSUE THREAD

**Issue by kushagra97pal** [mszhanyi/VSIXTorch#4]
![Screenshot (16)](https://user-images.githubusercontent.com/50581646/154853893-f1491a2e-9102-4a18-a430-8388b692e0fa.png)
I have followed the exact same steps as mentioned in https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001
please provide some help.
This is very important for me.
Best Regards,
Kushagra Pal

**Comment by mszhanyi** [comment]
did you install VS 2019 with the component 'Desktop Deveopment with C++'?

**Comment by kushagra97pal** [comment]
> did you install VS 2019 with the component 'Desktop Deveopment with C++'?

Thanks for your reply. I resolved that issue by resetting the settings of my visual studio. From this site:

https://social.msdn.microsoft.com/Forums/en-US/6ea597fe-fda5-464f-bcb7-a9b88bc7bf83/please-help-how-to-fix-error-e1696-file-source-cannot-be-opened-quotiostreamquot?forum=visualstudiogeneral

**Comment by putshua** [comment]
I also run into the same problem with VS 2022. 
I solved it by clicking Project -> Properties -> Configuration Properties -> General -> Windows SDK Version -> choose the corresponding version of your computer’s operating system or change the current Windows SDK Version.
